### ISSUE TITLE
How I fix this?

### ISSUE THREAD

**Issue by katlehotech** [blockchain/My-Wallet-V3-Frontend#1029]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

**Comment by plondon** [comment]
Hi @katlehotech, what command are you running? What is your operating system?

**Comment by katlehotech** [comment]
I'm using an ubuntu 16.04 server 1gig ram, 20 gig 

Commands
git clone https://github.com/blockchain/My-Wallet-V3-Frontend.git
cd My-Wallet-V3-Frontend
make server

**Comment by plondon** [comment]
@katlehotech are you still having issues running the wallet locally? Try running `make dist` instead.
