### ISSUE TITLE
No contact options for support

### ISSUE THREAD

**Issue by RebeccaWhit3** [blockchain/My-Wallet-V3-Frontend#1041]
There is no clear way to contact or reach Blockchain.info by email and the "contact support" link provided on this repository is useless (http://blockchain.zendesk.com/).

i.e. - I shouldn't have to create an issue here to get someones attention.

**Comment by kristovatlas** [comment]
Sorry to hear that you weren't satisfied with the support experience.

Our GitHub repositories are for developers only, and not a source for additional support resources.
