### ISSUE TITLE
TREZOR Connect integration

### ISSUE THREAD

**Issue by chren-de-large** [blockchain/My-Wallet-V3-Frontend#1054]
Hi,

I was thinking to integrate [TREZOR Connect](https://github.com/trezor/connect) into blockchain wallet (for example - first to receive and send bitcoins between wallets, later on possible login or 2FA). Would you consider it useful and in case i send you PR would you merge it if it pass quality tests? 

It seems to me good idea to integrate hot and cold wallet for seamless funds transfer.

**Comment by chren-de-large** [comment]
Hello? Hello? Hello? Is there anybody in there? Just nod if you can hear me, Is there anyone at home?

**Comment by plondon** [comment]
Hi @chren-de-large! This is an open source project so please feel more than welcome to open a pull request with your integration. Our devs will review it, leave comments and feedback, and eventually merge it if we decide it is something we want to include in our product.

Thanks
