### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by ramirez3805** [blockchain/My-Wallet-V3-Frontend#1215]
This isn't an issue at all but I have no idea where to ask this, I am using https://blockchain.info/api/blockchain_api for getting transactions and all that good stuff but I would like to soften my hits since there is a rate limit so my goal is only to request transactions from an address only between certain dates. Please, if this is possible and how, that would be amazing.

**Comment by jtormey** [comment]
Hey! Unfortunately we don't support selecting based on time. You can pass an `offset` parameter though, for selecting older transactions. Would that be sufficient for your use case?

**Comment by ramirez3805** [comment]
Thank you for answering my question! Yes I did see the offset parameter but that seems to skip a number of transaction. What I would like to do for example is say, give me only transactions for 2017. I don't see a way of doing that with the offset. I already have the blockchain parsed and into a database but it's definitely not efficient for me to download the entire blockchain each time and parse it, and put it into the database over and over again just to get new transactions. So I guess it doesn't suffice lol but it seems like there is no way unfortunately.

**Comment by jtormey** [comment]
Yeah, I can see how that's inconvenient, sorry. It would be kind of a hack, but maybe you could try finding transactions in the timeframe you're looking for by performing a binary search (using the offset parameter).

**Comment by ramirez3805** [comment]
I will look into it! Thank you for your time sir.
