### ISSUE TITLE
Send to unchecked private key should be disallowed

### ISSUE THREAD

**Issue by Rishodi** [blockchain/My-Wallet-V3-Frontend#1241]
Today on Reddit, a user reported 5 BTC lost because of a software error which caused him to send funds to the wrong address: https://www.reddit.com/r/Bitcoin/comments/6rnfjf/beware_of_blockchaininfo_i_just_lost_5_btc_due_to/

Coinbase recently introduced (and fixed) a bug in their app which caused QR codes for receiving addresses to be malformed according to the BIP 21 spec. The absence of a colon between "bitcoin" and the user's intended receiving address created a string which MyWallet recognized as a valid 40-44 character Base58 private key. Only after sending did the user realize that something was amiss, and that his funds had been sent to a different Bitcoin address than intended.

MyWallet will currently accept a private key in any usable format. This makes sense when importing a key into the wallet, but not when sending a transaction, since Wallet.isValidPrivateKey() will return true for many inputs that were not intended to be private keys. This behavior should be modified such that private keys are only accepted when sending a transaction if they can be checked for accuracy. E.g. WIF and mini private keys are acceptable, but private keys in any unchecked format should be considered invalid. Otherwise, the lack of error checking can lead to transactions unintentionally sent to unknown addresses, only recoverable if the user can recall what data was accidentally used as a key.

**Comment by mpfluger** [comment]
Thanks for your research. We have been following the Reddit thread and came to the same conclusion. We are preparing a PR to refactor and fix this issue. Please submit this issue to our bug bounty program as well: https://hackerone.com/blockchain.

**Comment by mpfluger** [comment]
Fixed in https://github.com/blockchain/My-Wallet-V3-Frontend/pull/1243. A version including the fix will be released shortly.
