### ISSUE TITLE
Unable to establish session

### ISSUE THREAD

**Issue by lijevowov-live** [blockchain/My-Wallet-V3-Frontend#1357]
Frontend started without errors, but:

Can not login to my account. Error: "Unable to establish session"
Can not create new account. Error: "Error generatin the entropyError: Received not ok statis: 404"

Frontend version in footer "vIntermediate  (MyWallet v3.39.5)"

**Comment by plondon** [comment]
Hi @lijevowov-live are you running the wallet locally instead of using the production build? Just in case, the production url is https://blockchain.info/wallet/#/login

**Comment by lijevowov-live** [comment]
Hi @plondon how I can make it work?

**Comment by lijevowov-live** [comment]
what i need to edit in my case?

**Comment by plondon** [comment]
Can you attach the request that is failing (404)? What is the error code?

**Comment by lijevowov-live** [comment]
cant find whats wrong. can I make error log here?

**Comment by plondon** [comment]
When you create a wallet the browser will make a request to `randombytes` and `uuid-generator` endpoints. Did one of these requests fail? What was the error message?

**Comment by lijevowov-live** [comment]
Have nothing in terminal. Lets start from login. Why I can not login to my account? Maybe I need to disable 2FA?

**Comment by plondon** [comment]
Check the console of your browser instead of the terminal, what errors do you get from the XHR requests in the network tab?

**Comment by plondon** [comment]
Have you tried using the latest stable version in production? https://blockchain.info/wallet/#/login

**Comment by lijevowov-live** [comment]
`Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  my-wallet-dd9a1cf64a4ce11e79ad233e61022c7dc1102533.min.js:1:275987
GET 
XHR 
http://localhost:8080/wallet/undefined/v2/randombytes [HTTP/1.1 404 Not Found 4ms]
Error: RNG.run  landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:368:3506
Error: Received not ok status: 404
Stack-Trace:
Blockchain</RNG.prototype.getServerEntropy@http://localhost:8080/wallet/js/my-wallet-dd9a1cf64a4ce11e79ad233e61022c7dc1102533.min.js:1:276357
Blockchain</RNG.prototype.run@http://localhost:8080/wallet/js/my-wallet-dd9a1cf64a4ce11e79ad233e61022c7dc1102533.min.js:1:274725
generateMnemonic@http://localhost:8080/wallet/js/my-wallet-dd9a1cf64a4ce11e79ad233e61022c7dc1102533.min.js:1:259597
Blockchain</MyWallet.createNewWallet@http://localhost:8080/wallet/js/my-wallet-dd9a1cf64a4ce11e79ad233e61022c7dc1102533.min.js:1:227357
Wallet/wallet.create/<@http://localhost:8080/wallet/js/wallet-cdec54b6a1be7f241c3c8d694365a119fecd7be2.min.js:11:2351
e/<@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:133:434
$eval@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:148:65
$digest@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:145:123
$apply@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:148:361
e/q<@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:161:386
f@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:46:490
mg/k.defer/c<@http://localhost:8080/wallet/js/landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:49:418
  landing-a88d8d994e6eb57b20c272981dc9af2c53196da5.min.js:368:3506
`
I cant use my own one?

**Comment by plondon** [comment]
Please create a file called `.env` in the root of your project. i.e `/path/to/project/My-Wallet-V3-Frontend/.env`

With contents:

ROOT_URL=https://blockchain.info
WEB_SOCKET_URL=wss://ws.blockchain.info/inv
API_DOMAIN=https://api.blockchain.info
WALLET_HELPER_URL=http://localhost:8081

**Comment by plondon** [comment]
@lijevowov-live did that help?
