### ISSUE TITLE
No Recovery Mnemonic after registration

### ISSUE THREAD

**Issue by azorpax** [blockchain/My-Wallet-V3-Frontend#137]
![screenshots](https://www.dropbox.com/s/bdi60vx13tjvxup/Screenshot%202015-09-26%2020.04.001.png)
https://www.dropbox.com/s/bdi60vx13tjvxup/Screenshot%202015-09-26%2020.04.001.png

**Comment by Sjors** [comment]
That doesn't good, but it's an issue on the original [My-Wallet](https://github.com/blockchain/) project, not in this brand new V3 version. I passed on your message.
