### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by piyewodasa83** [blockchain/My-Wallet-V3-Frontend#1371]
Hi all! 
I'm trying to run a local version of the project, but it's work only for localhost :( I mean I can't have access from 192.168.1.2 or 127.0.0.1. 

> Failed to load https://blockchain.info/uuid-generator?format=json&n=2&api_code=*** No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

Is it possible to solve this problem?
Thanks!

**Comment by plondon** [comment]
Any reason why you can't use localhost?
