### ISSUE TITLE
No login email

### ISSUE THREAD

**Issue by malroy89** [blockchain/My-Wallet-V3-Frontend#1395]
Hey guys! I can't get "login attempt" email. Yesterday i got one, but after i was logged out and tried to log in again, no more emails were received. Spam/etc. folders are empty. What can be the reason?

**Comment by plondon** [comment]
Hi malroy89! We had some issues with our email service. Are you still having issues?

**Comment by regulus33** [comment]
Still having issues with email. JS console shows 500 internal server error but UI displays: 'Please check your email to approve the log in attempt." No email sent. Not in spam folders etc.
