### ISSUE TITLE
wallet.my.wallet.bch is undefined

### ISSUE THREAD

**Issue by alcordo** [blockchain/My-Wallet-V3-Frontend#1415]
Wallet can't continue to login because of this error
![wallet my wallet bch is undefined](https://user-images.githubusercontent.com/34735051/34265692-a2654d88-e6b1-11e7-879e-c20d4503d4c8.JPG)

**Comment by jtormey** [comment]
This is a known issue effecting a subset of users, we will be releasing a fix for it in our next release. Thanks for reporting!

**Comment by plondon** [comment]
Thanks for your patience. This issue should now be resolved with the latest v1.30.6 release.

**Comment by alcordo** [comment]
Thanks.. confirmed..i can now login... Good job...
