### ISSUE TITLE
Unable to establish session

### ISSUE THREAD

**Issue by ricoxor** [blockchain/My-Wallet-V3-Frontend#1416]
Hello,
When I try to login I have this error : Unable to establish session
Someone can help me to fix my issue ?

**Comment by plondon** [comment]
Are you running the wallet locally or using blockchain.info/wallet?

**Comment by rasdotsu** [comment]
running locally same error

**Comment by smeaxal81** [comment]
Hello everyone! I get this error ' Unable to establish session' at My-Wallet-V3-Frontend too, i make local server, version 1.33.1
I try enter login/pass and get Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blockchain.info/wallet/sessions. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). my server run at local net

**Comment by dogbreath55** [comment]
Blockchain
