### ISSUE TITLE
hello Blockchain.

### ISSUE THREAD

**Issue by theteacherofficial** [blockchain/My-Wallet-V3-Frontend#1417]
Hello Sir ,

I tried many time to contact you do you provide support or just have support channel so that people think you are working on it and you never checked that ?

I have posted ticket almost 6 days ago and no one here to check that .....

please check that .

I have done an Exchange From My account Using Etherum to Bitcoin and its failed and My payment Got Held in Pending Order Id is "SFT-be601692-27fb-4689-adb9-578802ddb4ee"

Please check and Update me Asap

**Comment by prwelber** [comment]
Sorry you're having trouble. Github is for issues and activities related to our wallet software and open source development. For your issue, you should open a ticket with our support team here: https://support.blockchain.com/hc/en-us/requests/new?ticket_form_id=188186

They will get to you as soon as they can. Please include the Order Id with the rest of your information.

**Comment by theteacherofficial** [comment]
I have opened ticket almost 5 days ago and they never responded and never seen my ticket ....

I have done an Exchange From My account Using Etherum to Bitcoin and its failed and My payment Got Held in Pending Order Id is "SFT-be601692-27fb-4689-adb9-578802ddb4ee"

**Comment by theteacherofficial** [comment]
I am really exhausted after five days of wait and they never seen my ticket in that time .....
