### ISSUE TITLE
i realy have wallet and address

### ISSUE THREAD

**Issue by Bang631** [blockchain/My-Wallet-V3-Frontend#1421]
[Bitcoin-BlockChain-Balances-Extract-master.zip](https://github.com/blockchain/My-Wallet-V3-Frontend/files/1617084/Bitcoin-BlockChain-Balances-Extract-master.zip)
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/cf83bccef5411ee0565bd939514752c54db6239d/locales/vi-human.json#L8

**Comment by rogerwhitt** [comment]
what is all this I just want my 700.00 that u took from me

    On Tuesday, January 9, 2018, 7:15:39 PM EST, Ly Kim Bang <notifications@github.com> wrote:  
 
 
Bitcoin-BlockChain-Balances-Extract-master.zip
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/cf83bccef5411ee0565bd939514752c54db6239d/locales/vi-human.json#L8
