### ISSUE TITLE
No support for CashAddr addresses 

### ISSUE THREAD

**Issue by espectalll** [blockchain/My-Wallet-V3-Frontend#1432]
Bitcoin ABC, one of the main Bitcoin Cash implementations, has added a new address format called [CashAddr](https://www.bitcoinabc.org/cashaddr), which is the developers' recommended format. [Bitpay and Copay have already adopted it](https://blog.bitpay.com/cashaddr-bch-format/) by using it by default. My Wallet is currently incompatible and will detect CashAddr addresses as invalid, which makes it harder for people to do transactions in Bitcoin Cash.

Further resources:
Official specifications: https://github.com/Bitcoin-UAHF/spec/blob/master/cashaddr.md
Go converter implementation: https://github.com/schancel/cashaddr-converter
Angular 2 converter implementation: https://github.com/bitpay/address-translator

**Comment by kristovatlas** [comment]
Thanks! This being worked on. I'm going to close this for now.
