### ISSUE TITLE
CLose it

### ISSUE THREAD

**Issue by yerarse** [blockchain/My-Wallet-V3-Frontend#1438]
1JaEQrUmVn9u6Krc7RndxRCa5iXhgcBWCz

**Comment by plondon** [comment]
Was this an address generated by the wallet or outside of it?

**Comment by yerarse** [comment]
generated by the wallet

**Comment by plondon** [comment]
The wallet generates the extended private key for you so you don't have to worry about losing your private keys. What do you mean by 'Lost private key'?

**Comment by yerarse** [comment]
its on my blockchain wallet and its watch only. asks for private key

**Comment by yerarse** [comment]
blockchain/My-Wallet-V3-Frontend
