### ISSUE TITLE
"METADATA_FETCH_FAILED"

### ISSUE THREAD

**Issue by 144earth** [blockchain/My-Wallet-V3-Frontend#1454]
Everytime I login to blockchain wallet, on mywallet v.3.41.6, It says to click authorization link in email, so i go to my email in another tab, click the authorization link, which sends me to anew tab like this: "https://blockchain.info/wallet/#/authorize-approve/xxxxxx" 

Then It says SUCCESS with a green checkmark, and I go to my previous blockchain wallet tab, and after a few seconds, a red window pops up saying "METADATA_FETCH_FAILED"

This error has happened in Chrome, Firefox, Internet Explorer, Privatebrowsing/incognito both on and off....

Please help! Support is not helping with this .~!

**Comment by schnogz** [comment]
We have just released a complete rewrite of the entire wallet. Please try and login again and reach out to support if you're still have issues.
