### ISSUE TITLE
Question: does it incur fees if transferring funds between blockchain.info wallets?

### ISSUE THREAD

**Issue by nullart** [blockchain/My-Wallet-V3-Frontend#1480]
Question: does it incur fees if transferring funds between blockchain.info wallets?

I have seen wallet services provide no fees when transferring between their wallets. Any idea about these? or is it possible with blockchain's code?

thanks,

**Comment by dogbreath55** [comment]
Ok

**Comment by dogbreath55** [comment]
No

**Comment by plondon** [comment]
A 'transfer' between wallets is just sending from one address to another. This transaction must be validated on the blockchain and therefore requires you pay the network fee.
