### ISSUE TITLE
npm problem installation

### ISSUE THREAD

**Issue by yasalama** [blockchain/My-Wallet-V3-Frontend#1488]
Hello, I ve triend to follow the steps to install it in debian 8 and centos 7 , but i got problems during the makefile probably in npm packages : 
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:219:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:5
npm ERR!     at RegClient.get_ (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

Could you please provide which os is installed , and wich version of nodejs , npm .... ?

**Comment by plondon** [comment]
You may need to install babel-preset-latest

**Comment by yasalama** [comment]
that not resolved the problem , could you you please tell me which os version , which version that should work

**Comment by schnogz** [comment]
Install a more recent version of Node.  I would recommend using the latest LTS which is 8.11.2 but anything about 4.0.0 should fix your issue.
