### ISSUE TITLE
Reviewing Japanese translation

### ISSUE THREAD

**Issue by dabura667** [blockchain/My-Wallet-V3-Frontend#301]
I am reviewing the Japanese translations for both the front end and iOS.

Just double checking:
I should check the keys for en-human.json and translate them into Japanese as save it as `My-Wallet-V3-Frontend/locales/ja-human.json`? or should I overwrite ja-robot.json?

in my PR, should I delete ja-robot.json?

**Comment by Sjors** [comment]
Thanks for your help! Human translations should indeed go to a new file called `/locales/ja-human.json`. You should also remove the corresponding strings from `/locales/ja-robot.json`.

Note that `ja-robot.json` is outdated. `en-human.json` is the most up to date list of English strings.

iOs is a completely separate project: https://github.com/blockchain/My-Wallet-V3-iOS

cc @KMHouk @woudini

**Comment by Sjors** [comment]
We have human translations for Japanese now: https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/locales/ja-human.json
