### ISSUE TITLE
Please handle issues help

### ISSUE THREAD

**Issue by violetmoonlight** [blockchain/My-Wallet-V3-Frontend#303]
why the same line, the outside and inside are not the same
why time confirmation so long, has one day before
thanks for watching email
![zalo_screenshot_7_2_2016_1634778](https://cloud.githubusercontent.com/assets/17107796/12888703/e7ab8c04-cead-11e5-8649-694787cfdfac.png)
![zalo_screenshot_7_2_2016_1636228](https://cloud.githubusercontent.com/assets/17107796/12888702/e7a74bc6-cead-11e5-8a5e-1537cb772df8.png)

**Comment by Sjors** [comment]
Hi @violetmoonlight, please contact support [here](https://blockchain.zendesk.com). They're usually quick to help.
