### ISSUE TITLE
Chart for a specific Bitcoin address only shows for today

### ISSUE THREAD

**Issue by kireerik** [blockchain/My-Wallet-V3-Frontend#489]
I would like to get an all time chart on the following interface:
https://blockchain.info/charts/balance?address=3NVXE53nFT5x6D6V6j4qAZGcw8RR1wrNV9

Although the chart re-renders, clicking the different timespan links does not change the chart and the appropriate markers.

This issue is related to blockchain.info (https://github.com/zootreeves/blockchain.info/issues/11).

**Comment by alecalve** [comment]
This chart only shows the last 500 events for any given address. As this address is very popular (>24k transactions), 500 events only cover one day unfortunately

**Comment by kireerik** [comment]
I think it should work for unlimited events. May I ask you why do you limit it?

**Comment by alecalve** [comment]
Some addresses (like [1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp](https://blockchain.info/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp) have received million of transactions. Plotting all of them would put too much strain on our servers.

**Comment by kireerik** [comment]
I see. Are you planning to support unlimited events for this type of chart? For example you could cache the results on the server side to save on your server resources or delegate the calculations to the client side.

**Comment by alecalve** [comment]
There's no plan for it right now, but it's not out of the question.

**Comment by kireerik** [comment]
Can you recommend me an online service where I can see such a chart for all time?

**Comment by alecalve** [comment]
You could try [blockonomics](https://www.blockonomics.co/)'s wallet watcher, but I don't know if it'll do exactly what you wish.

**Comment by kireerik** [comment]
Thank you for recommending this service. Actually notifications are a great feature, but the graphs has the exact same limitations as your service. I think lots of users would appreciate if you could support unlimited events for graphs. It is crucial when you wish to explore and analyze the Blochain. I will describe my scenario just to show you how important can it be.

Recently I am experimenting with [BitMinister](https://bitminister.com/?ref=oengi
), which is a gambling or better to say ponzi game advertised as a Cloud Mining Platform. It has potential ponzi scheme characteristics. The linked [address chart](https://blockchain.info/charts/balance?address=3NVXE53nFT5x6D6V6j4qAZGcw8RR1wrNV9) is their basic address.

So in this case I would like to see and monitor (manually) their full balance history. So I can guess the best time to withdraw my funds and newer play again their game, because the operators will potentially shut down the service and potentially keep gamers' funds to take their profit.

**Comment by kireerik** [comment]
I have found the service that supports **all-time charts** for a **specific bitcoin address**. It is called [Blocktrail BTC](https://www.blocktrail.com/BTC).

However I think it would be great to have such a feature on [blockchain.info](https://blockchain.info/) as well.

**Comment by alecalve** [comment]
I didn't know about this Blocktrail feature, thanks for letting me know.

**Comment by kireerik** [comment]
Neither did I.

**Comment by alecalve** [comment]
Hum, I cannot reproduce, it works fine for me.

**Comment by kireerik** [comment]
Now it is working again for me as well. :) Anyway this temporary issue was address independent.
