### ISSUE TITLE
Export history should escape values containing commas

### ISSUE THREAD

**Issue by cdmackie** [blockchain/My-Wallet-V3-Frontend#576]
When using the Export History to create a CSV, any fiat values over 1000 contain thousand comma-separators.

e.g.

2015-01-01,00:00:00 GMT +00:00,sent,-4.3141,$ -1,157.26,$ -2,523.66,$ 268.25,......

This makes parsing a CSV difficult.

These values should either be escaped with quotes or not have commas.

i.e.

"$ -2,523.66" or $ -2523.66

I tried to track down the code to create a pull request, but it calls the Blockchain.API from exportHistory in wallet.service.js, which goes off to request "V2/export-history".  Couldn't find that.

**Comment by jtormey** [comment]
Thanks for pointing this out! Will close once fix is in master.
