### ISSUE TITLE
Leading space in receive address

### ISSUE THREAD

**Issue by hoglund** [blockchain/My-Wallet-V3-Frontend#740]
When copying the newly created address to my clipboard, either by using the button or marking the text with my cursor, a leading space is added to the address. This causes some other systems to think that the address is invalid. 

System info:
Mozilla Firefox 49.0

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

Linux laptop 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by plondon** [comment]
I believed @jtormey resolved this.

**Comment by jtormey** [comment]
Yes, fix will be live in next release.
