### ISSUE TITLE
make server error:

### ISSUE THREAD

**Issue by wwwmir3cq** [blockchain/My-Wallet-V3-Frontend#809]
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install th
e latest version of pug instead of jade

**Comment by plondon** [comment]
Hi @wwwmir3cq thanks for using the Blockchain Wallet!

That is just a warning and shouldn't necessarily stop you from using the wallet locally. If you are having trouble running the wallet, a full error report would be helpful.

Thanks!
