### ISSUE TITLE
Second password not working

### ISSUE THREAD

**Issue by servioj** [blockchain/My-Wallet-V3-Frontend#881]
when i insert the second password in my wallet it say is wrong, but i dont remember change it, and is not only happenig to me https://www.reddit.com/r/Bitcoin/comments/5lrt3q/blockchaininfo_secondary_password_not_working/
and I had  imported addresses there which i have no backup.

**Comment by Sjors** [comment]
Please contact support: https://support.blockchain.com/hc/en-us
